### ISSUE TITLE
how to define msg.script? 

### ISSUE THREAD

**Issue by isramos** [redconnect-io/node-red-contrib-rivescript#1]
simple question: how do I load the rivescript text content into msg.script? I assume it's inside a function node, but I can't find the right syntax. Should I load from file or can pass as a variable?

**Comment by stephenkeep** [comment]
Hi @isramos im using the template node to load the script. Here is the script im loading:

    // Learn stuff about our users.

    + my name is *
    - <set name=<formal>>Nice to meet you, <get name>.
    - <set name=<formal>><get name>, nice to meet you.

    + my name is <bot master>
    - <set name=<bot master>>That's my master's name too.

    + my name is <bot name>
    - <set name=<bot name>>What a coincidence! That's my name too!
    - <set name=<bot name>>That's my name too!

    + call me *
    - <set name=<formal>><get name>, I will call you that from now on.

    + i am * years old
    - <set age=<star>>A lot of people are <get age>, you're not alone.
    - <set age=<star>>Cool, I'm <bot age> myself.{weight=49}

    + i am a (@malenoun)
    - <set sex=male>Alright, you're a <star>.

    + i am a (@femalenoun)
    - <set sex=female>Alright, you're female.

    + i (am from|live in) *
    - <set location={formal}<star2>{/formal}>I've spoken to people from <get location> before.

    + my favorite * is *
    - <set fav<star1>=<star2>>Why is it your favorite?

    + i am single
    - <set status=single><set spouse=nobody>I am too.

    + i have a girlfriend
    - <set status=girlfriend>What's her name?

    + i have a boyfriend
    - <set status=boyfriend>What's his name?

    + *
    % whats her name
    - <set spouse=<formal>>That's a pretty name.

**Comment by isramos** [comment]
Thanks! I got it working.  

What you think about including a sample such as the one below somewhere in the docs?



`[{"id":"c0bc55e2.3f43a8","type":"inject","z":"b7e34592.481cb8","name":"","topic":"","payload":"My name is John","payloadType":"str","repeat":"","crontab":"","once":true,"x":116,"y":195,"wires":[["d3092281.2cf6e"]]},{"id":"89b13148.764ed","type":"rivescript-reply","z":"b7e34592.481cb8","name":"","x":571,"y":194,"wires":[["b402b027.4bfd5"]]},{"id":"d3092281.2cf6e","type":"function","z":"b7e34592.481cb8","name":"Prepare","func":"msg.payload = {\n    \"message\": msg.payload ,\n    \"username\":\"user1\"\n};\nreturn msg;","outputs":1,"noerr":0,"x":282.5,"y":195,"wires":[["ccdf96f5.332068"]]},{"id":"ccdf96f5.332068","type":"template","z":"b7e34592.481cb8","name":"Script","field":"script","fieldType":"msg","format":"text","syntax":"plain","template":"// Learn stuff about our users.\n\n+ my name is *\n- <set name=<formal>>Nice to meet you, <get name>.\n- <set name=<formal>><get name>, nice to meet you.\n\n+ my name is <bot master>\n- <set name=<bot master>>That's my master's name too.\n\n+ my name is <bot name>\n- <set name=<bot name>>What a coincidence! That's my name too!\n- <set name=<bot name>>That's my name too!\n\n+ call me *\n- <set name=<formal>><get name>, I will call you that from now on.\n\n+ i am * years old\n- <set age=<star>>A lot of people are <get age>, you're not alone.\n- <set age=<star>>Cool, I'm <bot age> myself.{weight=49}\n\n+ i am a (@malenoun)\n- <set sex=male>Alright, you're a <star>.\n\n+ i am a (@femalenoun)\n- <set sex=female>Alright, you're female.\n\n+ i (am from|live in) *\n- <set location={formal}<star2>{/formal}>I've spoken to people from <get location> before.\n\n+ my favorite * is *\n- <set fav<star1>=<star2>>Why is it your favorite?\n\n+ i am single\n- <set status=single><set spouse=nobody>I am too.\n\n+ i have a girlfriend\n- <set status=girlfriend>What's her name?\n\n+ i have a boyfriend\n- <set status=boyfriend>What's his name?\n\n+ *\n% whats her name\n- <set spouse=<formal>>That's a pretty name.","x":415,"y":194,"wires":[["89b13148.764ed"]]},{"id":"b402b027.4bfd5","type":"debug","z":"b7e34592.481cb8","name":"ShowReply","active":true,"console":"false","complete":"payload.reply","x":736,"y":193,"wires":[]}]`

**Comment by stephenkeep** [comment]
Thanks @isramos I have added your example flow to the README.md
