### ISSUE TITLE
Loading multiple scripts

### ISSUE THREAD

**Issue by isramos** [redconnect-io/node-red-contrib-rivescript#2]
I'd like to load the Eliza bot into node-red (https://github.com/aichaos/rivescript-js/tree/master/eg/brain).
Any suggestion on how to load multiple .rive script files in your node? (other than manually combining all .rive files into one) 
Options could be either load multiple "template" nodes, or load from a file or URL?

Thanks,
Igor

**Comment by stephenkeep** [comment]
hi @isramos, to load multiple and combine you can just do it with a design pattern like the aggregator pattern - https://www.redconnect.io/design-patterns/
